ignore:
  - "**/*.py"
  - "Makefile"
  - "template/*"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%